import React from 'react';
import './index.scss'

const Terminos = ()=>{
    return <>
        <div id='terminos'>
            <div className='terminos__container'>
                <h1>Términos, Acuerdos legales y Condiciones de uso Bitkkahpay</h1>
                <p>¡Le damos la Bienvenida a Bitkkahpay!</p>
                <p>El presente es un contrato entre Ud. y Bitkkah UO, compañía registrada en Estonia bajo el siguiente número de registro:….. y licencia Cripto – Exchange: …………… con dirección: en representación oficial de la plataforma Bitkkahpay.com.</p>
                <p>Bitkkahpay es una plataforma de pagos que permite a comerciantes y clientes realizar transacciones, compra y venta de productos y servicios seguras, mediante botones de pagos en Bitcoin. Bitkkahpay solo operar con bitcoin y en consecuencia es la única moneda aceptada para todas sus funcionalidades.</p>
                <p>Para utilizar la plataforma de pagos Bitkkahpay Ud. debe ser residente de los países aceptados por Bitkkahpay y al menos tener 18 años de edad o la mayoría de edad de su país.</p>
                <p>Estos Términos de uso de Bitkkahpay se celebran entre usted (en lo sucesivo, "usted" o "su") y los operadores de Bitkkahpay (como se define a continuación). Al acceder, descargar, usar o hacer clic en "Acepto" para aceptar cualquier Servicio de Bitkkahpay (como se define a continuación) proporcionado por Bitkkahpay (como se define a continuación), usted acepta que ha leído, entendido y aceptado todos los términos y condiciones estipulados en estos Términos de uso. Además, al utilizar algunas funciones de los Servicios, puede estar sujeto a términos y condiciones adicionales específicos aplicables a esas funciones.</p>
                <p>Lea los términos detenidamente, ya que rigen su uso de los Servicios de Bitkkahpay. ESTOS TÉRMINOS CONTIENEN DISPOSICIONES IMPORTANTES QUE INCLUYEN UNA DISPOSICIÓN DE ARBITRAJE QUE REQUIERE QUE TODAS LAS RECLAMACIONES SE RESUELVAN MEDIANTE ARBITRAJE LEGALMENTE VINCULANTE. RECONOCE Y ACEPTA QUE: (1) USTED ES CONSCIENTE DE LOS RIESGOS ASOCIADOS CON LAS OPERACIONES DE MONEDAS DIGITALES Y SUS DERIVADOS; (2) USTED ASUMIRÁ TODOS LOS RIESGOS RELACIONADOS CON EL USO DE LOS SERVICIOS DE Bitkkahpay Y LAS TRANSACCIONES DE MONEDAS DIGITALES Y SUS DERIVADOS; Y (3) Bitkkahpay NO SERÁ RESPONSABLE DE DICHOS RIESGOS O RESULTADOS ADVERSOS.</p>
                <p>Al acceder, usar o intentar usar los Servicios de Bitkkahpay en cualquier capacidad, usted reconoce que acepta y acepta estar sujeto a estos Términos. Si no está de acuerdo, no acceda a Bitkkahpay ni utilice los servicios de Bitkkahpay.</p>
                <p><strong>I. Definiciones</strong></p>
                <p>1. Bitkkahpay se refiere a un ecosistema que comprende los sitios web de Bitkkahpay (cuyos nombres de dominio incluyen, entre otros, https://www.Bitkkahpay.com), aplicaciones móviles, clientes, applets y otras aplicaciones que se desarrollan para ofrecer Servicios de Bitkkahpay, e incluye plataformas, sitios web y clientes operados de forma independiente dentro del ecosistema. En caso de discrepancia entre los términos de uso relevantes de las plataformas anteriores y el contenido de estos Términos, prevalecerán los respectivos términos aplicables de dichas plataformas.</p>
                <p>2. Los Operadores de Bitkkahpay se refieren a todas las partes que administran Bitkkahpay, incluidas, entre otras, personas jurídicas, organizaciones no incorporadas y equipos que brindan Servicios de Bitkkahpay y son responsables de dichos servicios. Por conveniencia, a menos que se indique lo contrario, las referencias a "Bitkkahpay" y "nosotros" en estos Términos se refieren específicamente a los Operadores de Bitkkahpay. BAJO ESTOS TÉRMINOS, LOS OPERADORES DE Bitkkahpay PUEDEN CAMBIAR COMO AJUSTES COMERCIALES DE Bitkkahpay, EN CUYO CASO, LOS OPERADORES CAMBIADOS DEBERÁN CUMPLIR SUS OBLIGACIONES BAJO ESTOS TÉRMINOS CON USTED Y LE PROPORCIONA SERVICIOS, Y DICHO CAMBIO NO AFECTA SUS DERECHOS E INTERESES BAJO ESTOS TÉRMINOS. ADICIONALMENTE, EL ALCANCE DE LOS OPERADORES Bitkkahpay PUEDE AMPLIARSE DEBIDO A LA PROVISIÓN DE NUEVOS SERVICIOS Bitkkahpay, EN CUYO CASO, SI CONTINÚA UTILIZANDO LOS SERVICIOS Bitkkahpay, SE CONSIDERARÁ QUE HA ACORDADO EJECUTAR CONJUNTAMENTE ESTOS TÉRMINOS CON LOS OPERADORES Bitkkahpay RECIENTEMENTE AÑADIDOS. EN CASO DE UNA DISPUTA, USTED DETERMINARÁ LAS ENTIDADES POR LAS CUALES ESTOS TÉRMINOS SE EJECUTAN CON USTED Y LAS CONTRAPARTIDAS DE LA DISPUTA, DEPENDIENDO DE LOS SERVICIOS ESPECÍFICOS QUE UTILICE Y DE LAS ACCIONES PARTICULARES QUE AFECTAN SUS DERECHOS O INTERESES.</p>
                <p>3. Los servicios de Bitkkahpay se refieren a varios servicios que le proporciona Bitkkahpay que se basan en tecnologías de Internet y / o blockchain y se ofrecen a través de los sitios web de Bitkkahpay, aplicaciones móviles, clientes y otras formas (incluidos los nuevos habilitados por el desarrollo tecnológico futuro). </p>
                <p>4. Las Reglas de la Plataforma de Bitkkahpay se refieren a todas las reglas, interpretaciones, anuncios, declaraciones, cartas de consentimiento y otros contenidos que han sido y serán publicados posteriormente por Bitkkahpay.</p>
                <p>5. Los usuarios se refieren a todas las personas, instituciones u organizaciones que acceden, descargan o utilizan Bitkkahpay o los Servicios de Bitkkahpay y que cumplen con los criterios y condiciones estipulados por Bitkkahpay. Si existen otros acuerdos para entidades tales como desarrolladores, distribuidores, creadores de mercado e intercambios de monedas digitales, se seguirán dichos acuerdos.</p>
                <p>6. Las monedas digitales se refieren a tokens o criptomonedas encriptados o digitales con un cierto valor que se basan en tecnologías blockchain y criptografía y se emiten y administran de forma descentralizada.</p>
                <p>7. Los activos digitales se refieren a las monedas digitales, sus derivados u otros tipos de activos digitalizados con un cierto valor.</p>
                <p>8. Las cuentas de Bitkkahpay se refieren a las cuentas virtuales fundamentales, incluidas las cuentas principales y las subcuentas, que Bitkkahpay abre para que los usuarios registren en Bitkkahpay su uso de los servicios de Bitkkahpay, transacciones, cambios de activos e información básica. Las cuentas de Bitkkahpay sirven como base para que los usuarios disfruten y ejerzan sus derechos en Bitkkahpay.</p>
                <p>9. El comercio de cripto a cripto se refiere a transacciones al contado en las que una moneda digital se intercambia por otra moneda digital.</p>
                <br/>
                <p><strong>II. Servicios de Bitkkahpay</strong></p>
                <p><strong>Botones de Pago - Condiciones para el Vendedor de Productos o Servicios</strong></p>
                <p>Una vez completado el registro y la verificación de identidad para su cuenta de Bitkkahpay, puede utilizar varios servicios de Bitkkahpay, que incluyen, la creación de botones de pago en sus tres versiones (botón de importe fijo, botón de pago variable y botón de pago para donaciones en moneda digital bitcoin)</p>
                <p>Bitkkahpay tiene derecho a:</p>
                <p>Proporcionar, modificar o cancelar, a su discreción, cualquier Servicio de Bitkkahpay en función de su plan de desarrollo.</p>
                <p>Permitir o prohibir el uso de algunos Servicios de Bitkkahpay por parte de algunos Usuarios de acuerdo con las Reglas de la Plataforma Bitkkahpay relevantes.</p>
                <p>1. Pautas de uso del servicio</p>
                <p>Siempre que cumpla constantemente con los términos y condiciones expresos establecidos en estos Términos, Bitkkahpay le otorga una licencia revocable, limitada, libre de regalías, no exclusiva, intransferible y no sublicencia le para acceder y utilizar los Servicios de Bitkkahpay a través de su computadora o dispositivos compatibles con Internet para sus fines comerciales siempre y cuando el producto o servicio que proporciones sea licito y no esté relacionado con pornografía, lavado de dinero, venta de sustancias prohibidas, narcotráfico, actividades relacionadas al terrorismo internacional y cualquier otra actividad ilícita de público conocimiento. Se le prohíbe utilizar los Servicios de Bitkkahpay de cualquier forma que no esté expresamente autorizada por estos Términos.</p>
                <p>Estos Términos solo otorgan una licencia limitada para acceder y utilizar los Servicios de Bitkkahpay. Por lo tanto, por la presente acepta que cuando utiliza los Servicios de Bitkkahpay, Bitkkahpay no transfiere los Servicios de Bitkkahpay o la propiedad o los derechos de propiedad intelectual de cualquier propiedad intelectual de Bitkkahpay a usted ni a nadie más. Todo el texto, gráficos, interfaces de usuario, interfaz visual, fotos, sonidos, diagramas de flujo de procesos, código informático (incluido código HTML), programas, software, productos, información y documentos, así como el diseño, estructura, selección, coordinación, La expresión, la apariencia y el diseño de cualquier contenido incluido en los servicios o proporcionado a través de los Servicios de Bitkkahpay son propiedad exclusiva, controlados y / o autorizados por los Operadores de Bitkkahpay o sus miembros, empresas matrices, licenciantes o afiliados.</p>
                <p>Bitkkahpay es propietario de cualquier comentario, sugerencia, idea u otra información o material (en lo sucesivo denominados colectivamente "Comentarios") sobre Bitkkahpay o los Servicios de Bitkkahpay que usted proporcione a través del correo electrónico, los Servicios de Bitkkahpay u otras formas. Por la presente, transfiere todos los derechos, propiedad e intereses de los Comentarios y todos los derechos de propiedad intelectual relacionados a Bitkkahpay. No tiene ningún derecho y, por la presente, renuncia a cualquier solicitud de reconocimiento o compensación basada en cualquier comentario, o cualquier modificación basada en cualquier comentario.</p>
                <p>2. Restricciones</p>
                <p>Cuando utiliza los Servicios de Bitkkahpay, acepta y se compromete a cumplir con las siguientes disposiciones:</p>
                <p>Durante el uso de los Servicios de Bitkkahpay, todas las actividades que realice deben cumplir con los requisitos de las leyes y regulaciones aplicables, estos Términos y diversas pautas de Bitkkahpay.</p>
                <p>Su uso de los Servicios de Bitkkahpay no debe violar los intereses públicos, la moral pública o los intereses legítimos de otros, incluidas las acciones que puedan interferir, interrumpir, afectar negativamente o prohibir a otros Usuarios el uso de los Servicios de Bitkkahpay.</p>
                <p>Sin el consentimiento previo por escrito de Bitkkahpay, no puede modificar, replicar, duplicar, copiar, descargar, almacenar, transmitir, difundir, transferir, desensamblar, difundir, publicar, eliminar o alterar ninguna declaración o etiqueta de derechos de autor, o licencia, sublicencia. , vender, reflejar, diseñar, alquilar, arrendar, etiqueta privada, otorgar garantías reales sobre las propiedades o cualquier parte de las propiedades, o crear sus obras derivadas o aprovechar cualquier parte de las propiedades.</p>
                <p><strong>Botones de Pago - Condiciones para el Comprador de Productos o Servicios</strong></p>
                <p>Como cliente de Bitkkahpay Ud. puede realizar compras de productos o servicios mediante botones de pagos instalados en páginas webs / tiendas por otros usuarios registrados y verificados por Bitkkahpay.</p>
                <p>1. Los botones de pago Bitkkahpay generan un código QR y proporcionan una wallet para que Ud. pueda realizar la compra de productos y servicios a través de bitcoin.</p>
                <p>2. Si Ud. como cliente / comprador no se encuentra registrado en Bitkkahpay la interface / Invoice y el botón de pago le pedirá proporciona un mail y una contraseña para generar un registro en nuestra plataforma de manera automática. Ud. comprende y acepta dicho registro como condición para la utilización de nuestra aplicación de pagos.</p>
                <p>3. Antes de realizar una compra mediante los botones de pago Bitkkahpay Ud. debe realizar la debida diligencia / investigación de la persona o empresa que vende el producto o servicio. Bitkkahpay no es mediador de la entrega de productos o servicios se sus clientes comerciantes, tampoco garantiza la entrega ni la calidad de los mismos. Es condición que Ud. acepte estos términos y condiciones antes de realizar cualquier tipo de compra mediante botones de pago Bitkkahpay.</p>
                <p>4. Bitkkahpay no contempla políticas de reembolso de dinero en caso de disconformidad en la compra de productos o servicios por parte del comprador, blokchain no permite realizar retrocesos de pagos mediante bitcoin. Ud. debe aceptar estas condiciones y tomar las medidas pertinentes antes de realizar un pago mediante nuestros botones de pago.</p>
                <p>5. Para realizar un pago a través de botones de pago Bitkkahpay Ud. podrá utilizar saldo disponible en su cuenta o bien pagar con fondos que posea en su wallet / Exchange.</p>
                <p><strong>Saldo de su cuenta Bitkkahpay en Bitcoin </strong></p>
                <p>Ud. puede tener saldo en su cuenta Bitkkahpay y disponer del mismo en todo momento. Dependiendo del uso que le de a su cuenta se presentaran las siguientes situaciones:</p>
                <p>1. Si Ud. tiene una cuenta en Bitkkahpay con la finalidad de vender sus productos y/o servicios acumulara saldo a medida que vuestros clientes realicen pagos mediante los botones de pago que tenga instalados en su web comercial o tienda de servicios. Podrá pedir un retiro de saldo a su Exchange / wallet de confianza cada vez que lo requiera sin límites ni restricciones.</p>
                <p>2. Si utiliza la cuenta solo para realizar compras mediante botones podrá tener saldo en su cuenta para simplificar la compra, pare este tipo de casos la plataforma tiene una opción interna de recarga de saldo mediante bitcoin.</p>
                <p>3. Bitkkahpay también le permite envío de saldo entre cuentas Bitkkahpay. Ud. podrá enviar bitcoin entre usuarios Bitkkahpay.</p>
                <p><strong>Estado de cuenta Bitkkahpay</strong></p>
                <p>Bitkkahpay proporciona un estado de cuenta en tiempo real para todas sus transacciones entre ellas podemos detallar las siguientes: </p>
                <p>1. Recargas: Son todas las recargas de saldos mediante la opción RECARGA CUENTA vía bitcoin para diferentes fines, disponer de saldo para compras instantáneas mediante botones de pago o bien para realizar una transferencia interna de cuenta Bitkkahpay a otra cuenta Bitkkahpay.</p>
                <p>2. Ingresos por Ventas: Son todos los ingresos en bitcoin que Ud. reciba en su cuenta mediante botones de pagos. Bitkkahpay proporcionara un apartado con el detalle de la venta, importe, código de productos, datos de comprador (Nombre, mail, Teléfono, id cuanta Bitkkahpay etc.) a fin de disponer de la información necesaria para realizar el correspondiente contacto y posterior entrega del producto servicio.</p>
                <p><strong>Integraciones Avanzadas</strong></p>
                <p>Bitkkahpay puede proporcionar app y sistemas de integración avanzadas para caso de empresas que requieran interactuar mediante base de datos para simplificar entrega de productos online, accesos a áreas de productos específicos etc. Para tal fin de Bitkkahpay cuenta con un departamento comercial ara reuniones programadas vía Zoom de ser necesario.</p>
                <br/>
                <p><strong>III. Limites en la responsabilidad – Seguridad Bitkkahpay </strong></p>
                <p>Bitkkahpay adopta un enfoque integral para proteger sus cuentas. Nuestro equipo de expertos ha incorporado una serie de medidas complejas para prevenir el robo de fondos e información.</p>
                <p>Es responsabilidad del Ud. aplicar las medidas de seguridad sugeridas para proteger su cuenta. Bitkkahpay no será responsable de perdidas debido al mal uso de las políticas sugeridas:</p>
                <p>1. CONTRASEÑAS: Incorporar una contraseña de 12 dígitos alfa numérica incluyendo símbolos, mayúsculas y minúsculas. Se recomienda no alojar dicha contraseña en el ordenador ni en teléfonos móviles. Tampoco dejar predeterminada dicha contraseña. </p>
                <p>En la actualidad se ha comprobado que ingresar al ordenador mediante hackeos de IP Wifi es el método más utilizado para apropiarse de datos de accesos a una cuenta.</p>
                <p>2. SEGUNDO FACTOR: Verificación en dos pasos (Google Authenticator). Activar el segundo factor es un elemento esencial para resguardar el acceso a su cuenta. Debe realizarlo de manera inmediata.</p>
                <p>3. MAIL VINCULADO A BITKKAHPAY: Se recomienda tomar mismas medidas de seguridad de CONTRASEÑAS para el mail que vincule a su cuenta Bitkkahpay. Bitkkahpay enviara información sensible a dicho correo.</p>

                <p>Cordialmente,</p>
                <p>Grupo Bitkkahpay</p>


            </div>

        </div>
    
    </>
}

export default Terminos